STEP01: IMPORTING REQUIRED LIBRARIES FOR EDA

1. NumPy       :-  for numerical operations and mathematical calculations
2. Pandas      :-  for data loading, manipulation, and analysis
3. Matplotlib  :-  for basic data visualization (charts and graphs)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

STEP02: DATA LOADING

- Reading the CSV file and storing it in a DataFrame called 'dataset'.

In [2]:
dataset = pd.read_csv("data_science_salaries.csv")
dataset

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium
...,...,...,...,...,...,...,...,...,...,...,...
6594,Staff Data Analyst,Entry-level,Contract,Hybrid,2020,Canada,60000,CAD,44753,Canada,Large
6595,Staff Data Analyst,Executive-level,Full-time,On-site,2020,Nigeria,15000,USD,15000,Canada,Medium
6596,Machine Learning Manager,Senior-level,Full-time,Hybrid,2020,Canada,157000,CAD,117104,Canada,Large
6597,Data Engineer,Mid-level,Full-time,Hybrid,2020,Austria,65000,EUR,74130,Austria,Large
6598,Data Scientist,Senior-level,Full-time,On-site,2020,Austria,80000,EUR,91237,Austria,Small

STEP03: DATASET INSPECTION

- In this step, I explore the dataset to understand its structure,
- data types, missing values, and basic patterns before analysis

In [4]:
# 01 Check shape of dataset (rows, columns)
# This tells how big the dataset is
data_shape = dataset.shape
print(f"1. Dataset Shape (rows, columns): {data_shape}\n")


# 02 View column names
# Helps understand what features are available
data_columns = dataset.columns
print(f"2. Dataset Columns:")
for col in data_columns:
    print(col)

1. Dataset Shape (rows, columns): (6599, 11)

2. Dataset Columns:
job_title
experience_level
employment_type
work_models
work_year
employee_residence
salary
salary_currency
salary_in_usd
company_location
company_size

In [5]:
# 03 View first 5 rows
# Gives a quick idea of how data looks
dataset.head()

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium

In [6]:
# 04 Get basic info about dataset
# Shows data types, non-null values, memory usage
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6599 entries, 0 to 6598
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_title           6599 non-null   object
 1   experience_level    6599 non-null   object
 2   employment_type     6599 non-null   object
 3   work_models         6599 non-null   object
 4   work_year           6599 non-null   int64
 5   employee_residence  6599 non-null   object
 6   salary              6599 non-null   int64
 7   salary_currency     6599 non-null   object
 8   salary_in_usd       6599 non-null   int64
 9   company_location    6599 non-null   object
 10  company_size        6599 non-null   object
dtypes: int64(3), object(8)
memory usage: 567.2+ KB

In [7]:
# 05 Statistical summary of numeric columns
# Helps understand distribution (mean, min, max, etc.)
dataset.describe()

         work_year        salary  salary_in_usd
count  6599.000000  6.599000e+03    6599.000000
mean   2022.818457  1.792833e+05  145560.558569
std       0.674809  5.263722e+05   70946.838070
min    2020.000000  1.400000e+04   15000.000000
25%    2023.000000  9.600000e+04   95000.000000
50%    2023.000000  1.400000e+05  138666.000000
75%    2023.000000  1.875000e+05  185000.000000
max    2024.000000  3.040000e+07  750000.000000

In [11]:
# 06 Check missing values in each column
# Helps identify data quality issues
missing_values = dataset.isnull().sum()
print(f"1. Missing Values of Dataset(Column-wise):\n{missing_values}\n")


# 07 Check duplicate rows
# Ensures there is no repeated data
duplicate_count = dataset.duplicated().sum()
print(f"2. Duplicate Rows Count: {duplicate_count}")

1. Missing Values of Dataset(Column-wise):
job_title             0
experience_level      0
employment_type       0
work_models           0
work_year             0
employee_residence    0
salary                0
salary_currency       0
salary_in_usd         0
company_location      0
company_size          0
dtype: int64

2. Duplicate Rows Count: 0

In [17]:
# 08 Unique values in important columns
# Helps understand category diversity

print(f"job_title: {dataset["job_title"].nunique()}")
print(f"experience_level: {dataset["experience_level"].nunique()}")
print(f"employment_type: {dataset["employment_type"].nunique()}")
print(f"work_models: {dataset["work_models"].nunique()}")
print(f"work_year: {dataset["work_year"].nunique()}")
print(f"company_size: {dataset["company_size"].nunique()}")

job_title: 132
experience_level: 4
employment_type: 4
work_models: 3
work_year: 5
company_size: 3

In [21]:
# 09 Frequency of categorical columns
# Shows most common categories in each column with their counts sorted in descending order

print(f"{dataset["job_title"].value_counts()}\n")
print(f"{dataset["experience_level"].value_counts()}\n")
print(f"{dataset["employment_type"].value_counts()}\n")
print(f"{dataset["work_models"].value_counts()}\n")
print(f"{dataset["company_size"].value_counts()}\n")

job_title
Data Engineer                1307
Data Scientist               1243
Data Analyst                  910
Machine Learning Engineer     629
Analytics Engineer            246
                             ...
Deep Learning Researcher        1
Power BI Developer              1
Marketing Data Scientist        1
AI Product Manager              1
Sales Data Analyst              1
Name: count, Length: 132, dtype: int64

experience_level
Senior-level       4105
Mid-level          1675
Entry-level         565
Executive-level     254
Name: count, dtype: int64

employment_type
Full-time    6552
Contract       19
Part-time      16
Freelance      12
Name: count, dtype: int64

work_models
On-site    3813
Remote     2561
Hybrid      225
Name: count, dtype: int64

company_size
Medium    5860
Large      569
Small      170
Name: count, dtype: int64